### ISSUE TITLE
Missing user upload restrictions

### ISSUE THREAD

**Issue by FoxxMD** [NRicode/GigaPaste#3]
If this app is designed to be used only in a local/closed/trusted network please update the readme.

However, if the intention was for it to be used publicly, on the internet, it is missing the ability to restrict uploads. I don't want some random person to be able to upload gigabytes of files to my instance or use my link shortener for spam.

Please implement some kind of gating for the creation functionality of links/pastebin/uploads.

**Comment by jmarler** [comment]
I came here to request exactly this. Some kind of upload authentication is necessary here. Even if it is something as simple as IP based restriction, or a simple password, this will be quickly abused as soon as someone writes a Shodan rule for it. The last thing you want is for users to get into trouble for distributing CSAM due to a lack of upload restrictions.

**Comment by NRicode** [comment]
> If this app is designed to be used only in a local/closed/trusted network please update the readme.
> 
> However, if the intention was for it to be used publicly, on the internet, it is missing the ability to restrict uploads. I don't want some random person to be able to upload gigabytes of files to my instance or use my link shortener for spam.
> 
> Please implement some kind of gating for the creation functionality of links/pastebin/uploads.

Can I get some examples / references for that? AFAIK it's almost impossible to keep out spam from services like this. Even pastebin has bots spamming their site 24/7.

**Comment by NRicode** [comment]
I thought that most people would use reverse proxy to handle authentication. But yeah, think having a built in authentication is a good idea, working on it.

**Comment by FoxxMD** [comment]
Authentication via reverse proxy is fine if the audience of users are people you already know. 

The real benefit of pastebin/link shortening/file sharing websites, especially when self hosted, is being able to share those things with the public internet while being able to delete or make them inaccessible when you want (control your data).

**Comment by NRicode** [comment]
> Authentication via reverse proxy is fine if the audience of users are people you already know.
> 
> The real benefit of pastebin/link shortening/file sharing websites, especially when self hosted, is being able to share those things with the public internet while being able to delete or make them inaccessible when you want (control your data).

I don't get what you mean, if you set passwords to upload file, it is not accessible even by anyone even your hosting provider due to encryption. The issue I saw here is that the public can access your site if you are not running it within a reverse proxy. You have total control of your data by the password mechanism already.

What exactly are you proposing? Can you give example?

**Comment by FoxxMD** [comment]
I'm not proposing anything, I'm trying to get across the point that the type of software you've written is generally designed for public use but yours is not.

In my original comment

> If this app is designed to be used only in a local/closed/trusted network please update the readme.

and you've just said

> this project was made to quickly share files between devices e.g from your pc to your phone / other people.

but the readme for this project is written as if this is is not the case:

* nowhere does it mention the lack of user control (what this issue is for)
* does not specify that there is no file/content CRUD
* does not contextualize what you have said here IE this is for local use only
* the section "why its better than other similar apps" leads me to believe I can use it _like other similar apps_ but that is not the case re: above points

Other similar apps such as [chibisafe](https://chibisafe.moe) and [picoshare](https://github.com/mtlynch/picoshare) have robust admin, file, and user controls.

___

I'm not trying to diss your project or tell you you've done it wrong. I'm trying to convey that the average user's idea of what this is for as well as how you've advertised it contradict your actual intended use and how you've designed it. 

You need to clarify and contextualize the intended use in the readme so users aren't mislead, or worse use it without realizing it isn't intended for public access.

**Comment by NRicode** [comment]
> I'm not proposing anything, I'm trying to get across the point that the type of software you've written is generally designed for public use but yours is not.
> 
> In my original comment
> 
> > If this app is designed to be used only in a local/closed/trusted network please update the readme.
> 
> and you've just said
> 
> > this project was made to quickly share files between devices e.g from your pc to your phone / other people.
> 
> but the readme for this project is written as if this is is not the case:
> 
> * nowhere does it mention the lack of user control (what this issue is for)
> * does not specify that there is no file/content CRUD
> * does not contextualize what you have said here IE this is for local use only
> * the section "why its better than other similar apps" leads me to believe I can use it _like other similar apps_ but that is not the case re: above points
>   
>   * Other similar apps such as [chibisafe](https://chibisafe.moe) and [picoshare](https://github.com/mtlynch/picoshare) have robust admin, file, and user controls.
>   * but you've said
>     
>     * > the ability to delete your upload is unnecessary feature
> 
> I'm not trying to diss your project or tell you you've done it wrong. I'm trying to convey that the average user's idea of what this is for as well as how you've advertised it contradict your actual intended use and how you've designed it.
> 
> You need to clarify and contextualize the intended use in the readme so users aren't mislead, or worse use it without realizing it isn't intended for public access. Tell users in unambiguous terms:
> 
> > this project was made to quickly share files between devices **on a trusted network** e.g from your pc to your phone / **friends / family / trusted local users.**

Got it, just added login page, would appreciate if you can help me try it out, thank you!

**Comment by FoxxMD** [comment]
Tested with these settings in `settings.json`

```json
{
    "password": "test",
    "enablePassword": true
}
```

* The auth page provides no feedback if the password is incorrect. The response from `POST /auth` on form submission returns an empty response with `200 OK` status
* Using the correct password causes the auth page to be returned again so it's not possible to use the app when a password is enabled, at all 

![image](https://github.com/user-attachments/assets/a46e77ab-1424-417e-820e-77e57db48cee)

**Comment by NRicode** [comment]
> Tested with these settings in `settings.json`
> 
> ```json
> {
>     "password": "test",
>     "enablePassword": true
> }
> ```
> 
> * The auth page provides no feedback if the password is incorrect. The response from `POST /auth` on form submission returns an empty response with `200 OK` status
> * Using the correct password causes the auth page to be returned again so it's not possible to use the app when a password is enabled, at all
> 
> ![image](https://private-user-images.githubusercontent.com/4663766/374287261-a46e77ab-1424-417e-820e-77e57db48cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjk4NjksIm5iZiI6MTcyODMyOTU2OSwicGF0aCI6Ii80NjYzNzY2LzM3NDI4NzI2MS1hNDZlNzdhYi0xNDI0LTQxN2UtODIwZS03N2U1N2RiNDhjZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTkzMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTcyMTM1MTkxNDNmY2VlNTYxNjg1NzVkOWExNmU4ZDYyNTg1ZGMzMzE1M2Y0ZDNjYTY3ZDhkNzkzZTIyMzU5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0tRe8rmaNnzcxzCXCnou9R7XEtWbhImZY20Groa9_1k)

Will add some feedback for wrong password. As for the redirection stuff, I cannot reproduce it. I fixed some stuff from my latest commit, did you test it on the latest version?
