### ISSUE TITLE
No default text size limit prevents any link or pastebin upload

### ISSUE THREAD

**Issue by FoxxMD** [NRicode/GigaPaste#4]
Without a `settings.json` file with `textSizeLimitMB` defined trying to create a URL or use as pastebin returns a "100% Copy Link New" result page with no errors but the Copy Link button does nothing.

Investigating the docker log shows `http: request body too large`.

After adding `textSizeLimitMB` to settings it looks like a correct result page is generated.

I did not test them but its likely the other size limit settings do not have default settings as well. The result page should not be returned if there is an error on the server.

**Comment by NRicode** [comment]
values inside settings.json cannot be removed, PR is welcome to do the checks inside settings.go
